# -*- coding: utf-8 -*-
"""adding_NER's.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JZirwyTHrSOJqED74iE6RyVirK2YZTv

Importing Libraries
"""

import spacy
nlp = spacy.load("en_core_web_sm")

str1=input("Give me a string: ")

doc=nlp(str1)

def show_ents(doc):
    if doc.ents:
        for ent in doc.ents:
            print(ent.text+' - '+ent.label_+' - '+str(spacy.explain(ent.label_)))
    else:
        print('No named entities found.')

show_ents(doc)

from spacy.tokens import Span

from spacy.matcher import PhraseMatcher
matcher = PhraseMatcher(nlp.vocab)

p_list = ['conference', 'con-ference']
p_patterns = [nlp(text) for text in p_list]

matcher.add('newproduct', None, *p_patterns)

matches = matcher(doc)

matches

print(matches[1])

PROD = doc.vocab.strings[u'EVENT']
new_ents = [Span(doc, match[1],match[2],PROD) for match in matches]
doc.ents = list(doc.ents) + new_ents

print(doc.ents)

show_ents(doc)

