# -*- coding: utf-8 -*-
"""pos_tagging_using_nltk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Char3i9nnQPMzwicy3FTTc22XiFtM38

Importing NLTK

# New Section
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

"""Strings"""

string1=input("Give me a String: ")

print("Original String: "+string1)
string1=string1.lower()
print("Lower-Case: " + string1)

"""Tokenization"""

from nltk.tokenize import word_tokenize
tokens=word_tokenize(string1)
print(tokens)

"""Stop Words"""

from nltk.corpus import stopwords
t_w_sw=[]
stop_w=stopwords.words('english')
for word in tokens:
  if word not in stop_w:
    t_w_sw.append(word)

print(t_w_sw)

"""POS Tagging"""

#Parts of Speech tagging using tokens including stopWOrds
pos=nltk.pos_tag(tokens)
print(pos)

#POS tagging without StopWords
pos_w=nltk.pos_tag(t_w_sw)
print(pos_w)

"""Word Matching"""

pattern1=["soon","whistle"]
matched_words=[]
for word in tokens:
  if word in pattern1:
    matched_words.append(word)

print(matched_words)